name: Adding New ECR

on:
  repository_dispatch:
     type: [event-triggered-by-jira]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: testing values
      run: |
          echo team name is ${{ github.event.client_payload.teamName }}
          echo new ecr name is ${{ github.event.client_payload.ecrName }}
    
    - name: curent data in ${{ github.event.client_payload.teamName }}.tf file
      run: cat ${{ github.event.client_payload.teamName }}.tf

    - name: running command to add module team1.tf file
      run: ./script.sh ${{ github.event.client_payload.teamName }} ${{ github.event.client_payload.ecrName }}

    - name: Check if module is added or not in ${{ github.event.client_payload.teamName }}.tf file
      run: cat ${{ github.event.client_payload.teamName }}.tf

    - name: Pushing the new code to Repository. 
      run: |
          git status
          git add .
          git commit -m "Added new ECR code"
          git push origin ${{ github.event.client_payload.branchName }}
      
    - name: Pushing the new code to Repository. 
      run: |
          gh auth login --with-token < mytoken.txt
          gh pr create
